version: "3.4"
services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgrespw
    ports:
      - 5433:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - 5672:5672
      - 15672:15672
  consul:
    image: hashicorp/consul:latest
    command: consul agent -dev -log-level=warn -ui -client=0.0.0.0 -bind 0.0.0.0
    ports: 
      - "8500:8500"
      - "8600:8600/udp"
    hostname: consul
    restart: always
    extra_hosts:
        - "host.docker.internal:host-gateway"