AWSTemplateFormatVersion: 2010-09-09
Description: KT template for ECS cluster

Parameters:

  VpcStack:
    Type: String
    Description: Name of VPC stack to build off of
    Default: kt-vpc
  
  DomainName:
    Type: String
    Description: The DNS name of an existing Amazon Route 53 hosted zone e.g. king-transports.com
    AllowedPattern: (?!-)[a-zA-Z0-9-.]{1,63}(?<!-)
    ConstraintDescription: must be a valid DNS zone name.
    Default: king-transports.com
    
  ApiDomainName:
    Type: String
    Description: The full API domain name e.g. api.king-transports.com
    AllowedPattern: (?!-)[a-zA-Z0-9-.]{1,63}(?<!-)
    ConstraintDescription: must be a valid DNS zone name.
    Default: api.king-transports.com
    
Resources:

  KtEcsSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
        GroupName: "kt-ecs-sg"
        GroupDescription: Allow http to client host
        VpcId:
          Fn::ImportValue: !Sub ${VpcStack}-vpc-id
        SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 8080
          ToPort: 8080
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: 0.0.0.0/0
        SecurityGroupEgress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 8080
          ToPort: 8080
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 5432
          ToPort: 5432
          CidrIp: 0.0.0.0/0

  KtEcsRole:
    Type: 'AWS::IAM::Role'
    Properties:
      RoleName: kt-ecs-role
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
              - ec2.amazonaws.com
              - ecs.amazonaws.com
              - ecs-tasks.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Path: /
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy
        - arn:aws:iam::aws:policy/AmazonECS_FullAccess
        - arn:aws:iam::aws:policy/CloudWatchFullAccessV2
        - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryFullAccess
        - arn:aws:iam::aws:policy/AmazonSQSFullAccess


  KtAlb:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      IpAddressType: ipv4
      Scheme: internet-facing
      SecurityGroups:
        - !Ref KtEcsSecurityGroup
      Subnets:
        - Fn::ImportValue: !Sub ${VpcStack}-public-subnet-a-id
        - Fn::ImportValue: !Sub ${VpcStack}-public-subnet-b-id
      Type: application

  # TODO: Get hosted Zone id from domain name
  SSLCertificate:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: !Ref 'ApiDomainName'
      ValidationMethod: DNS
      DomainValidationOptions:
        - DomainName: !Ref 'ApiDomainName'
          HostedZoneId: Z03079513ORY4C37190FP
  
  # ListenerCertificate:
    # Type: AWS::ElasticLoadBalancingV2::ListenerCertificate
    # Properties: 
      # Certificates: 
        # - CertificateArn: !Ref Certificate
      # ListenerArn: !Ref KtListener
    # DependsOn: KtListener  

  KtListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      Certificates: 
        - CertificateArn: !Ref SSLCertificate
      DefaultActions:
        - Type: fixed-response
          FixedResponseConfig:        
            ContentType: text/plain
            MessageBody: "Not Found"
            StatusCode: 404
      Port: 443
      Protocol: HTTPS
      LoadBalancerArn: !Ref KtAlb
       
  KtEcsCluster:
    Type: AWS::ECS::Cluster
    Properties:
        ClusterName: "kt-ecs-cluster"
    
Outputs:

  KtEcsClusterExport:
    Description: A reference to the created ECS Cluster
    Value: !Ref KtEcsCluster
    Export:
      Name: !Sub ${AWS::StackName}-ecs-cluster

  KtEcsSecurityGroupExport:
    Description: A reference to the created SG
    Value: !Ref KtEcsSecurityGroup
    Export:
      Name: !Sub ${AWS::StackName}-default-security-group

  KtEcsRoleExport:
    Description: A reference to the created IAM Role
    Value: !Ref KtEcsRole
    Export:
      Name: !Sub ${AWS::StackName}-default-role

  KtAlbArnExport:
    Description: A reference to the created ALB
    Value: !Ref KtAlb
    Export:
      Name: !Sub ${AWS::StackName}-alb-arn
      
  KtAlbDnsExport:
    Description: A reference to the created ALB
    Value: 
      Fn::GetAtt: KtAlb.DNSName
    Export:
      Name: !Sub ${AWS::StackName}-alb-dns

  KtElbListenerArnExport:
    Description: A reference to the created listener
    Value: !Ref KtListener
    Export:
      Name: !Sub ${AWS::StackName}-elb-listener-arn