AWSTemplateFormatVersion: "2010-09-09"
Description: ""
Parameters:
  CodeBuildProjectName:
    Description: Name of the code build project
    Type: String
    Default: "KingTransports-Common"
  EcrImageName:
    Description: Docker image name in ECR
    Type: String
    Default: "king-transports/common"
    
Resources:

    CodeBuildProject:
        Type: "AWS::CodeBuild::Project"
        Properties:
            Name: !Ref CodeBuildProjectName
            Source: 
                GitCloneDepth: 1
                GitSubmodulesConfig: 
                    FetchSubmodules: false
                InsecureSsl: false
                Location: "https://github.com/tmedanovic/king-transports.git"
                ReportBuildStatus: false
                Type: "GITHUB"
            Artifacts: 
                Type: "NO_ARTIFACTS"
            Cache: 
                Type: "NO_CACHE"
            Environment: 
                ComputeType: "BUILD_GENERAL1_SMALL"
                EnvironmentVariables: 
                  - 
                    Name: "AWS_DEFAULT_REGION"
                    Type: "PLAINTEXT"
                    Value: !Ref AWS::Region
                  - 
                    Name: "AWS_ACCOUNT_ID"
                    Type: "PLAINTEXT"
                    Value: !Ref AWS::AccountId
                  - 
                    Name: "IMAGE_REPO_NAME"
                    Type: "PLAINTEXT"
                    Value:  !Sub "${EcrImageName}"
                  - 
                    Name: "DOCKERHUB_USERNAME"
                    Type: "PLAINTEXT"
                    Value: "tomislav.medanovic@gmail.com"
                  - 
                    Name: "DOCKERHUB_PASS"
                    Type: "PLAINTEXT"
                    Value: "REPLACEME"
                  - 
                    Name: "IMAGE_TAG"
                    Type: "PLAINTEXT"
                    Value: "Latest"
                  - 
                    Name: "CODEARTIFACT_DOMAIN"
                    Type: "PLAINTEXT"
                    Value: "king-transports"
                  - 
                    Name: "CODEARTIFACT_REPO"
                    Type: "PLAINTEXT"
                    Value: "king-transports"
                Image: "aws/codebuild/standard:7.0"
                ImagePullCredentialsType: "CODEBUILD"
                PrivilegedMode: false
                Type: "LINUX_CONTAINER"
            ServiceRole: !Sub "codebuild-${CodeBuildProjectName}-service-role"
            TimeoutInMinutes: 60
            QueuedTimeoutInMinutes: 480
            EncryptionKey: !Sub "arn:aws:kms:${AWS::Region}:${AWS::AccountId}:alias/aws/s3"
            BadgeEnabled: false
            LogsConfig: 
                CloudWatchLogs: 
                    Status: "ENABLED"
                S3Logs: 
                    Status: "DISABLED"
                    EncryptionDisabled: false
            Visibility: "PRIVATE"